# Fastfile

default_platform(:ios)

platform :ios do
  desc "Run unit & UI tests using xctestplan"
  lane :run_tests do
    run_tests(
      scheme: "CiCdProjekt",
      test_plan: "CiCdProject.xctestplan",
      devices: ["iPhone 14"]
    )
  end

  desc "Build and archive for development"
  lane :dev_build do
    build_app(
      scheme: "CiCdProjekt",
      export_method: "development"
    )
  end

  desc "Setup match certificates for CI"
  lane :setup_ci do
    match(
      type: "development",
      readonly: true
    )
  end
end
