# Fastfile

default_platform(:ios)

platform :ios do
  desc "Run unit & UI tests using xctestplan"
  lane :ci_tests do
    run_tests(
      scheme: "CiCdProjekt",
      testplan: "CiCdProjekt"
    )
  end

  desc "Build and archive for development"
  lane :dev_build do
    build_app(
      scheme: "CiCdProjekt",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "de.arianamini.test.CiCdProjekt" => "match Development de.arianamini.test.CiCdProjekt"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Setup match certificates for CI"
  lane :ci_setup do
    match(
      type: "development",
      readonly: true
    )
  end
end
