# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and run tests"
  lane :test do
    run_tests(
      scheme: "CiCdProjekt",
      devices: ["iPhone 14"],
      test_plan: "CiCdProject.xctestplan"
    )
  end
  
  desc "Build and archive for App Store"
  lane :build do
    build_app(scheme: "CiCdProjekt")
  end
  
  desc "development"
  lane :dev_build do
      match(type: "development")
      build_app(scheme: "CiCdProjekt")
  end
end