# .github/workflows/ios.yml
name: iOS Build & Test (Develop)

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
jobs:
    build-and-test:
        runs-on: macos-14

        steps:
            - name: 📦 Checkout code
              uses: actions/checkout@v4

            - name: 🛠️ Setup Xcode 15.4
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: "15.4"

            - name: ✅ Enable file system synchronized groups
              run: echo 'IDEFileSystemSynchronizedGroupsAreEnabled=YES' >> $GITHUB_ENV

            - name: 🔧 Install Ruby & Fastlane
              run: |
                  gem install bundler
                  bundle install

            - name: 🔐 Setup CI certificates
              run: bundle exec fastlane ci_setup
              env:
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
                  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
                  APP_STORE_CONNECT_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}

            - name: 🧪 Run tests
              run: bundle exec fastlane ci_tests
              env:
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
                  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
                  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
                  APP_STORE_CONNECT_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
